function pack(consoleId, hint, rows) {
  return rows.map(([name, search]) => ({
    id: `${consoleId}-${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
    name,
    search: search || `${hint} ${name}`,
  }));
}

export const OFFICIAL_PERIPHERALS = {
  nes: pack("nes", "NES", [
    ["NES Controller"],
    ["NES Zapper"],
    ["NES Advantage"],
    ["NES Max"],
    ["R.O.B."],
    ["Power Pad", "NES Power Pad"],
    ["NES Four Score"],
    ["NES Satellite"],
  ]),
  snes: pack("snes", "Super Nintendo", [
    ["SNES Controller"],
    ["Super Scope"],
    ["Super Advantage", "SNES Super Advantage"],
    ["SNES Mouse"],
    ["Super Multitap", "Super NES Multitap"],
    ["Score Master", "SNES Score Master"],
  ]),
  n64: pack("n64", "Nintendo 64", [
    ["N64 Controller"],
    ["Rumble Pak"],
    ["Controller Pak"],
    ["Expansion Pak"],
    ["Transfer Pak"],
    ["Jumper Pak"],
    ["Voice Recognition Unit", "Nintendo 64 Voice Recognition Unit"],
    ["N64 Mouse"],
  ]),
  gamecube: pack("gamecube", "GameCube", [
    ["GameCube Controller"],
    ["WaveBird"],
    ["Game Boy Player"],
    ["DK Bongos"],
    ["GameCube Microphone"],
    ["Broadband Adapter", "GameCube Broadband Adapter"],
    ["Modem Adapter", "GameCube Modem Adapter"],
    ["Component Video Cable", "GameCube Component Cable"],
  ]),
  wii: pack("wii", "Wii", [
    ["Wii Remote"],
    ["Nunchuk"],
    ["Wii MotionPlus"],
    ["Classic Controller"],
    ["Classic Controller Pro"],
    ["Wii Balance Board"],
    ["Wii Wheel"],
    ["Wii Zapper"],
    ["Wii Speak"],
    ["Sensor Bar", "Wii Sensor Bar"],
    ["Wii LAN Adapter"],
  ]),
  wiiu: pack("wiiu", "Wii U", [
    ["Wii U GamePad"],
    ["Wii U Pro Controller"],
    ["Wii Remote"],
    ["Nunchuk"],
    ["Wii U Microphone"],
    ["GameCube Controller Adapter", "Wii U GameCube Adapter"],
    ["Wii U LAN Adapter"],
  ]),
  switch: pack("switch", "Nintendo Switch", [
    ["Joy-Con"],
    ["Nintendo Switch Pro Controller"],
    ["Nintendo Switch Dock"],
    ["Joy-Con Charging Grip"],
    ["Joy-Con Wheel"],
    ["Ring-Con"],
    ["Leg Strap", "Nintendo Switch Ring Fit Leg Strap"],
    ["USB LAN Adapter", "Nintendo Switch LAN Adapter"],
    ["Nintendo Switch Online N64 Controller"],
    ["NES Controller", "Nintendo Switch Online NES Controller"],
  ]),
  switch2: pack("switch2", "Nintendo Switch 2", [
    ["Joy-Con 2"],
    ["Nintendo Switch 2 Pro Controller"],
    ["Nintendo Switch 2 Dock"],
    ["Joy-Con 2 Charging Grip"],
    ["Nintendo Switch 2 Camera"],
    ["GameCube Controller", "Nintendo Switch 2 GameCube Controller"],
    ["USB-C LAN Adapter", "Nintendo Switch LAN Adapter"],
  ]),
  gb: pack("gb", "Game Boy", [
    ["Game Boy Camera"],
    ["Game Boy Printer"],
    ["Game Link Cable"],
    ["Four Player Adapter", "Game Boy Four Player Adapter"],
    ["Battery Pack", "Game Boy battery pack"],
  ]),
  gbc: pack("gbc", "Game Boy Color", [
    ["Game Boy Camera"],
    ["Game Boy Printer"],
    ["Game Link Cable"],
    ["Mobile Adapter GB"],
  ]),
  gba: pack("gba", "Game Boy Advance", [
    ["Game Boy Advance Wireless Adapter"],
    ["Game Boy Advance Link Cable"],
    ["e-Reader", "Nintendo e-Reader"],
    ["Play-Yan"],
    ["Game Boy Player"],
    ["GBA SP Headphones", "Game Boy Advance SP headphones"],
  ]),
  ds: pack("ds", "Nintendo DS", [
    ["Nintendo DS Headset"],
    ["Nintendo DS Rumble Pak"],
    ["Guitar Grip", "Nintendo DS Guitar Grip"],
    ["Nintendo Wi-Fi USB Connector"],
    ["Play-Yan Micro"],
    ["Pokéwalker"],
  ]),
  "3ds": pack("3ds", "Nintendo 3DS", [
    ["Circle Pad Pro"],
    ["Nintendo 3DS Charging Cradle"],
    ["NFC Reader/Writer", "Nintendo 3DS NFC Reader"],
    ["New Nintendo 3DS Charging Cradle"],
    ["Nintendo 3DS Stand"],
  ]),
  ps1: pack("ps1", "PlayStation", [
    ["PlayStation Controller"],
    ["Dual Analog Controller"],
    ["DualShock"],
    ["PlayStation Multitap"],
    ["PlayStation Memory Card"],
    ["PocketStation"],
    ["PlayStation Mouse"],
    ["PlayStation Analog Joystick"],
    ["PlayStation Link Cable"],
  ]),
  ps2: pack("ps2", "PlayStation 2", [
    ["DualShock 2"],
    ["PlayStation 2 Multitap"],
    ["DVD Remote Controller", "PlayStation 2 DVD remote"],
    ["PlayStation 2 Memory Card"],
    ["Network Adaptor", "PlayStation 2 Network Adaptor"],
    ["PlayStation 2 HDD", "PlayStation 2 hard disk drive"],
    ["EyeToy"],
    ["PlayStation 2 Headset"],
  ]),
  ps3: pack("ps3", "PlayStation 3", [
    ["Sixaxis"],
    ["DualShock 3"],
    ["PlayStation Move"],
    ["PlayStation Move Navigation Controller"],
    ["PlayStation Eye"],
    ["PlayStation 3 Blu-ray Remote"],
    ["PlayStation 3 Wireless Keypad"],
    ["PlayStation 3 Headset"],
    ["PlayStation 3 Memory Card Adapter"],
  ]),
  ps4: pack("ps4", "PlayStation 4", [
    ["DualShock 4"],
    ["DualShock 4 Charging Station"],
    ["PlayStation Camera"],
    ["PlayStation VR"],
    ["PlayStation VR Aim Controller"],
    ["PlayStation Move"],
    ["PlayStation Gold Wireless Headset"],
    ["PlayStation 4 Media Remote"],
    ["PlayStation 4 Vertical Stand"],
  ]),
  ps5: pack("ps5", "PlayStation 5", [
    ["DualSense"],
    ["DualSense Edge"],
    ["DualSense Charging Station"],
    ["PULSE 3D Wireless Headset"],
    ["PULSE Elite"],
    ["PULSE Explore"],
    ["HD Camera", "PlayStation 5 HD Camera"],
    ["Media Remote", "PlayStation 5 Media Remote"],
    ["PlayStation VR2"],
    ["PlayStation VR2 Sense Controllers"],
    ["PlayStation 5 Vertical Stand"],
    ["PlayStation 5 Disc Drive"],
  ]),
  psp: pack("psp", "PlayStation Portable", [
    ["PSP Camera"],
    ["PSP GPS Receiver"],
    ["PSP Microphone"],
    ["PSP Headset"],
    ["PSP 1seg Tuner"],
    ["PSP Cradle"],
    ["PSP Battery Pack"],
    ["Memory Stick Duo"],
  ]),
  vita: pack("vita", "PlayStation Vita", [
    ["PlayStation Vita Memory Card"],
    ["PlayStation TV"],
    ["PlayStation Vita Cradle"],
    ["PlayStation Vita L2/R2 Grip"],
    ["PlayStation Vita Pouch"],
  ]),
  xbox: pack("xbox", "original Xbox", [
    ["Xbox Duke Controller"],
    ["Xbox Controller S"],
    ["Xbox Memory Unit"],
    ["Xbox Communicator", "Xbox Live Communicator"],
    ["Xbox DVD Playback Kit"],
    ["Xbox System Link Cable"],
  ]),
  360: pack("360", "Xbox 360", [
    ["Xbox 360 Wired Controller"],
    ["Xbox 360 Wireless Controller"],
    ["Xbox 360 Headset"],
    ["Xbox 360 Wireless Headset"],
    ["Kinect", "Kinect Xbox 360"],
    ["Xbox 360 Play and Charge Kit"],
    ["Xbox 360 Chatpad"],
    ["Xbox 360 Hard Drive"],
    ["Xbox 360 Media Remote"],
    ["Xbox 360 Wireless Racing Wheel"],
  ]),
  xb1: pack("xb1", "Xbox One", [
    ["Xbox One Controller"],
    ["Xbox Elite Controller"],
    ["Xbox Elite Series 2"],
    ["Kinect for Xbox One"],
    ["Xbox Chat Headset"],
    ["Xbox Stereo Headset Adapter"],
    ["Xbox Play and Charge Kit"],
    ["Xbox One Digital TV Tuner"],
    ["Xbox One Media Remote"],
  ]),
  xss: pack("xss", "Xbox Series", [
    ["Xbox Wireless Controller"],
    ["Xbox Elite Series 2"],
    ["Xbox Stereo Headset"],
    ["Xbox Series X Storage Expansion Card"],
    ["Xbox Rechargeable Battery Kit"],
    ["Xbox Wireless Adapter for Windows"],
  ]),
  mastersystem: pack("mastersystem", "Sega Master System", [
    ["Master System Control Pad"],
    ["Master System Control Stick"],
    ["Light Phaser"],
    ["Sports Pad", "Sega Sports Pad"],
    ["Paddle Control", "Sega Paddle Control"],
    ["Sega 3-D Glasses"],
    ["FM Sound Unit", "Sega Mark III FM Sound Unit"],
  ]),
  genesis: pack("genesis", "Sega Mega Drive", [
    ["Three-Button Control Pad", "Mega Drive Control Pad"],
    ["Six-Button Control Pad", "Mega Drive Six Button"],
    ["Sega Team Player"],
    ["Mega Mouse"],
    ["Sega Menacer"],
    ["Sega Activator"],
    ["Sega CD"],
    ["Sega 32X"],
    ["Master System Converter"],
  ]),
  saturn: pack("saturn", "Sega Saturn", [
    ["Saturn Control Pad"],
    ["Saturn 3D Control Pad"],
    ["Saturn Mission Stick"],
    ["Saturn Twin Stick"],
    ["Saturn Mouse"],
    ["Saturn 6 Player Adaptor"],
    ["Virtua Gun"],
    ["Saturn Floppy Drive"],
    ["Saturn MPEG Card"],
    ["Saturn RAM Cartridge"],
  ]),
  dreamcast: pack("dreamcast", "Dreamcast", [
    ["Dreamcast Controller"],
    ["Jump Pack", "Dreamcast Jump Pack"],
    ["Visual Memory Unit"],
    ["Dreamcast Keyboard"],
    ["Dreamcast Mouse"],
    ["Dreamcast Fishing Controller"],
    ["Dreamcast Arcade Stick"],
    ["Dreamcast Microphone"],
    ["Dreamcast VGA Box"],
    ["Dreamcast Broadband Adapter"],
    ["Dreameye"],
    ["Dreamcast Racing Controller"],
  ]),
  pc: pack("pc", "PC", [
    ["Xbox Wireless Controller"],
    ["Xbox Wireless Adapter for Windows"],
    ["Xbox Elite Series 2"],
    ["DualShock 4"],
    ["DualSense"],
    ["Nintendo Switch Pro Controller"],
  ]),
};

export function officialFor(consoleId) {
  return OFFICIAL_PERIPHERALS[consoleId] || [];
}
